transmission:
  username: YOUR_TRANSMISSION_USERNAME
  password: YOUR_TRANSMISSION_PASSWORD
  baseurl: http://localhost:9091/transmission/rpc

tautulli:
  apikey: YOUR_TAUTULLI_API_KEY
  baseurl: http://localhost:8181/api/v2

throttling:
  stream_count: 2

speed: # KB/s
  normal:
    download: 7000
    upload: 1000
  throttled:
    download: 3000
    upload: 100